[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["website/**"]

[deploy]
healthcheckPath = "/about"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
